apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-operator
  namespace: argocd
spec:
  project: tooling
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tooling
  source:
    chart: intel-device-plugins-operator
    repoURL: https://intel.github.io/helm-charts/
    targetRevision: 0.30.0
    helm:
      releaseName: intel-device-plugins-operator
