kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage-pihole-config
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage-pihole-dnsmasq
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer